sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

  - platform: template
    sensors:
      friendly_date:
        friendly_name: "Date"
        icon_template: mdi:calendar
        value_template: >
          {{ as_timestamp(strptime(states('sensor.date'), '%Y-%m-%d')) | timestamp_custom("%a, %b %d") }}
      friendly_time:
        friendly_name: "Time"
        icon_template: mdi:clock
        value_template: >
          {{ as_timestamp(now()) | timestamp_custom("%I:%M %p") }}

  - platform: command_line
    name: CPU Temperature
    unique_id: pihole_cpu_temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"

  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m