sensor:
  - platform: rest
    name: awair_sensors
    unique_id: awair_sensors
    resource: http://10.10.10.20/air-data/latest
    json_attributes:
      - score
      - temp
      - humid
      - co2
      - voc
      - pm25
    value_template: 'OK'

template:
  - sensor:
    - name: awair_score
      unique_id: awair_score
      state: '{{ states.sensor.awair_sensors.attributes["score"] }}'
      unit_of_measurement: '%'

    - name: awair_temp
      unique_id: awair_temp
      state: >-
        {% set t = states.sensor.awair_sensors.attributes["temp"] | float %}
        {{ ((t)*9/5)+32 }}
      device_class: temperature
      state_class: measurement
      unit_of_measurement: '°F'

    - name: awair_humidity
      unique_id: awair_humidity
      state: '{{ states.sensor.awair_sensors.attributes["humid"] }}'
      device_class: humidity
      state_class: measurement
      unit_of_measurement: '%'

    - name: awair_co2
      unique_id: awair_co2
      state: '{{ states.sensor.awair_sensors.attributes["co2"] }}'
      unit_of_measurement: 'ppm'
      device_class: carbon_dioxide
      state_class: measurement

    - name: awair_voc
      unique_id: awair_voc
      state: '{{ states.sensor.awair_sensors.attributes["voc"] }}'
      unit_of_measurement: 'ppb'
      device_class: volatile_organic_compounds
      state_class: measurement

    - name: awair_pm25
      unique_id: awair_pm25
      state: '{{ states.sensor.awair_sensors.attributes["pm25"] }}'
      unit_of_measurement: 'μg/m³'
      state_class: measurement
      device_class: pm25
