sensor:
  - platform: template
    sensors:
      # tesla_est_battery_range_mi:
      #   friendly_name: Estimated Range (mi)
      #   unit_of_measurement: mi
      #   icon_template: mdi:gauge
      #   value_template: >
      #     {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609) | round(2) }}

      # tesla_rated_battery_range_mi:
      #   friendly_name: Rated Range (mi)
      #   unit_of_measurement: mi
      #   icon_template: mdi:gauge
      #   value_template: >
      #     {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609) | round(2) }}

      # tesla_ideal_battery_range_mi:
      #   friendly_name: Ideal Range (mi)
      #   unit_of_measurement: mi
      #   icon_template: mdi:gauge
      #   value_template: >
      #     {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609) | round(2) }}

      tesla_odometer_mi:
        friendly_name: Odometer (mi)
        unit_of_measurement: mi
        icon_template: mdi:counter
        value_template: >
          {{ (states('sensor.tesla_odometer') | float / 1.609) | round(2) }}

      tesla_speed_mph:
        friendly_name: Speed (MPH)
        unit_of_measurement: mph
        icon_template: mdi:speedometer
        value_template: >
          {{ (states('sensor.tesla_speed') | float / 1.609) | round(2) }}

      tesla_elevation_ft:
        friendly_name: Elevation (ft)
        unit_of_measurement: ft
        icon_template: mdi:image-filter-hdr
        value_template: >
          {{ (states('sensor.tesla_elevation') | float * 3.2808 ) | round(2) }}

template:
  - sensor:
    - name: tesla_garage_temperature
      unique_id: "tesla_garage_temperature"
      device_class: temperature
      state_class: measurement
      availability: >
        {{ is_state('sensor.tesla_geofence', 'Home') }}
      unit_of_measurement: °F
      state: >
        {{ states('sensor.tesla_outside_temp') }}

mqtt:
  sensor: 
  - name: tesla_display_name
    state_topic: "teslamate/cars/1/display_name"
    icon: mdi:car
    unique_id: tesla_display_name

  - name: tesla_state
    state_topic: "teslamate/cars/1/state"
    icon: mdi:car-connected
    unique_id: tesla_state

  - name: tesla_geofence
    state_topic: "teslamate/cars/1/geofence"
    icon: mdi:earth
    unique_id: tesla_geofence

  - name: tesla_latitude
    state_topic: "teslamate/cars/1/latitude"
    unit_of_measurement: °
    icon: mdi:crosshairs-gps
    unique_id: tesla_latitude

  - name: tesla_longitude
    state_topic: "teslamate/cars/1/longitude"
    unit_of_measurement: °
    icon: mdi:crosshairs-gps
    unique_id: tesla_longitude

  - name: tesla_shift_state
    state_topic: "teslamate/cars/1/shift_state"
    icon: mdi:car-shift-pattern
    unique_id: tesla_shift_state

  - name: tesla_power
    state_topic: "teslamate/cars/1/power"
    device_class: power
    unit_of_measurement: W
    icon: mdi:flash
    unique_id: tesla_power

  - name: tesla_speed
    state_topic: "teslamate/cars/1/speed"
    unit_of_measurement: "km/h"
    icon: mdi:speedometer
    unique_id: tesla_speed

  - name: tesla_elevation
    state_topic: "teslamate/cars/1/elevation"
    unit_of_measurement: m
    icon: mdi:image-filter-hdr
    unique_id: tesla_elevation

  - name: tesla_inside_temp
    state_topic: "teslamate/cars/1/inside_temp"
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:thermometer-lines
    unique_id: tesla_inside_temp

  - name: tesla_outside_temp
    state_topic: "teslamate/cars/1/outside_temp"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: °C
    icon: mdi:thermometer-lines
    unique_id: tesla_outside_temp

  - name: tesla_odometer
    state_topic: "teslamate/cars/1/odometer"
    unit_of_measurement: km
    icon: mdi:counter
    unique_id: tesla_odometer

  - name: tesla_battery_level
    state_topic: "teslamate/cars/1/battery_level"
    device_class: battery
    unit_of_measurement: "%"
    icon: mdi:battery-80
    unique_id: tesla_battery_level
    
  - name: tesla_usable_battery_level
    state_topic: "teslamate/cars/1/usable_battery_level"
    unit_of_measurement: "%"
    icon: mdi:battery-80
    unique_id: tesla_usable_battery_level

  - name: tesla_charge_energy_added
    state_topic: "teslamate/cars/1/charge_energy_added"
    device_class: energy
    unit_of_measurement: kWh
    state_class: total_increasing
    icon: mdi:battery-charging
    unique_id: tesla_charge_energy_added

  - name: tesla_charge_limit_soc
    state_topic: "teslamate/cars/1/charge_limit_soc"
    unit_of_measurement: "%"
    icon: mdi:battery-charging-100
    unique_id: tesla_charge_limit_soc

  - name: tesla_charger_actual_current
    state_topic: "teslamate/cars/1/charger_actual_current"
    device_class: current
    unit_of_measurement: A
    icon: mdi:lightning-bolt
    unique_id: tesla_charger_actual_current

  - name: tesla_charger_phases
    state_topic: "teslamate/cars/1/charger_phases"
    icon: mdi:sine-wave
    unique_id: tesla_charge_phases

  - name: tesla_charger_power
    state_topic: "teslamate/cars/1/charger_power"
    device_class: power
    unit_of_measurement: kW
    icon: mdi:lightning-bolt
    unique_id: tesla_charger_power

  - name: tesla_charger_voltage
    state_topic: "teslamate/cars/1/charger_voltage"
    device_class: voltage
    unit_of_measurement: V
    icon: mdi:lightning-bolt
    unique_id: tesla_charger_voltage

  - name: tesla_time_to_full_charge
    state_topic: "teslamate/cars/1/time_to_full_charge"
    unit_of_measurement: h
    icon: mdi:clock-outline
    unique_id: tesla_time_to_full_charge

